ci:
    autofix_commit_msg: '[pre-commit.ci] auto fixes from pre-commit hooks'
    autofix_prs: true
    autoupdate_commit_msg: '[pre-commit.ci] pre-commit autoupdate'
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: check-yaml
    -   id: pretty-format-json
        args: ['--autofix', '--indent=4']
    -   id: trailing-whitespace
-   repo: https://github.com/pycqa/flake8
    rev: '7.0.0'
    hooks:
    -   id: flake8
        args: ['--select=E9,F63,F7,F82']
