name: CI

on: [push, pull_request]

jobs:
  CI:

    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: test
        python-version: 3.8
    - name: Conda info
      run: |
        conda env update -n test -f tools/conda_envs/jobmanager.yaml
        conda info
        conda list
    - name: Install package
      run: |
        pip install -e ".[tests]"
    - name: Run tests
      run: |
        pytest --cov=jobmanager --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./coverage.xml
        verbose: true
